---
- name: "copy motd file to /etc/motd"
  copy: 
    src: motd
    dest: /etc/motd
    owner: root 
    group: root 
    mode: '644'

- name: "Clone Bashcrawl"
  ansible.builtin.git:
    repo: https://gitlab.com/slackermedia/bashcrawl.git
    dest: /usr/local/bashcrawl
    version: master

- name: "Ensure profile.d exists"
  ansible.builtin.file:
    path: /etc/profile.d/
    state: directory

- name: "Add Bashcrawl to the system PATH using profile.d"
  ansible.builtin.lineinfile:
    path: /etc/profile.d/bashcrawl.sh
    create: yes
    line: 'export PATH=$PATH:/usr/local/bashcrawl'

- name: Create a symlink for all users to "cd bashcrawl"
  ansible.builtin.file:
    src: /usr/local/bashcrawl
    dest: /usr/local/bin/bashcrawl
    state: link

- name: "Clone Hauberk"
  ansible.builtin.git:
    repo: https://github.com/munificent/hauberk.git
    dest: /usr/local/hauberk
    version: master

- name: "Download Flutter"
  ansible.builtin.get_url: 
    url: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.1-stable.tar.xz
    dest: /usr/local/flutter_linux_3.16.1-stable.tar.xz
  notify: 
    - Unpack Flutter

- name: "Unpack Flutter"
  ansible.builtin.unarchive:
    src: /usr/local/flutter_linux_3.16.1-stable.tar.xz
    dest: /opt/
  when: "'Unpack Flutter' in ansible_run_tags"

- name: "Add Flutter to path using profile.d"
  ansible.builtin.lineinfile:
    path: /etc/profile.d/flutter.sh
    create: yes
    line: 'export PATH=$PATH:/opt/flutter/bin'

- name: Reload profile to apply changes
  ansible.builtin.command: "/bin/bash -l -c 'for file in /etc/profile.d/*; do source $file; done'"

- name: "Build Hauberk"
  ansible.builtin.command: make serve
  args:
    chdir: /usr/local/hauberk