---
- name: "copy motd file to /etc/motd"
  copy: 
    src: motd
    dest: /etc/motd
    owner: root 
    group: root 
    mode: '644'

- name: "Clone Bashcrawl"
  ansible.builtin.git:
    repo: https://gitlab.com/slackermedia/bashcrawl.git
    dest: /usr/local/bashcrawl
    version: master

- name: "Ensure profile.d exists"
  ansible.builtin.file:
    path: /etc/profile.d/
    state: directory

- name: "Add Bashcrawl to the system PATH using profile.d"
  ansible.builtin.lineinfile:
    path: /etc/profile.d/bashcrawl.sh
    create: yes
    line: 'export PATH=$PATH:/usr/local/bashcrawl'

- name: Create a symlink for all users to "cd bashcrawl"
  ansible.builtin.file:
    src: /usr/local/bashcrawl
    dest: /usr/local/bin/bashcrawl
    state: link

- name: "Clone Hauberk"
  ansible.builtin.git:
    repo: https://github.com/munificent/hauberk.git
    dest: /usr/local/hauberk
    version: master
    mode: '0775'

- name: "Download Flutter"
  ansible.builtin.get_url: 
    url: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.1-stable.tar.xz
    dest: /usr/local/flutter_linux_3.16.1-stable.tar.xz
  register: download_Flutter
    
- name: "Unpack Flutter"
  ansible.builtin.unarchive:
    src: /usr/local/flutter_linux_3.16.1-stable.tar.xz
    dest: /opt/
    remote_src: yes
  when: download_Flutter.changed
  register: flutter_unpack_result

- name: "Add Flutter to path using profile.d"
  ansible.builtin.lineinfile:
    path: /etc/profile.d/flutter.sh
    create: yes
    line: 'export PATH=$PATH:/opt/flutter/bin'
  when: flutter_unpack_result.changed
  register: flutter_path

- name: "Reload profile to apply changes"
  ansible.builtin.command: "/bin/bash -l -c 'for file in /etc/profile.d/*; do source $file; done'"
  when: flutter_path.changed
  register: flutter_in_path

- name: "Appease Git"
  ansible.builtin.command: git config --global --add safe.directory /opt/flutter
  when: flutter_in_path.changed
  register: git_happy

- name: "Debug PATH"
  ansible.builtin.debug:
    var: ansible_env.PATH
  when: git_happy.changed
 
#- name: "Build Hauberk"
#  ansible.builtin.command:
#    argv:
#      - "make serve"
#    chdir: "/usr/local/hauberk"
#    environment:
#      PATH: "{{ ansible_env.PATH }}:/opt/flutter/bin"
#  when: git_happy.changed

#- name: "Build Hauberk"
#  ansible.builtin.command: make serve
# args:
#   chdir: "/usr/local/hauberk"
 # environment:
 #   PATH: "{{ ansible_env.PATH }}:/opt/flutter/bin"
 # become_user: uoljwh
 # when: git_happy.changed